-- LinenFlow™ Migration 012: ลูกค้าจริงของ LaundryKing + ตารางราคาต่อลูกค้า
--
-- ที่มา: ไฟล์ใบแจ้งหนี้รายเดือน มิ.ย. 2569 (ฐานข้อมูลลูกค้า/*.xlsx) 42 ไฟล์
--        = ลูกค้า 38 ราย (3 ไฟล์เป็นใบ "ค่าเช่าผ้า" ของลูกค้าที่มีอยู่แล้ว
--          จึงถูกรวมเข้าลูกค้าเดิมในรูป service_type='rental')
--
-- ประเด็นสำคัญเชิงธุรกิจ: **ราคาต่อหน่วยเป็นราคาเฉพาะลูกค้า** ไม่ใช่ราคากลาง
--   เช่น ผ้าเช็ดตัว (SKU '1') คิด 8/9/10/12 บาท ต่างกันตามลูกค้า
--   ฉะนั้นราคาจึงอยู่ในตาราง customer_price_lists ไม่ใช่ linen_articles.unit_price
--
-- รหัส SKU ใช้ชุดเดียวกับ catalog (migration 009): product + size + activity
--   ทุกรหัสที่ใช้จริงในใบแจ้งหนี้ (98 รหัส) ถอดกลับเข้า catalog ได้ครบ ไม่มีรหัสใหม่
--   หมายเหตุการเขียนรหัส: ใบแจ้งหนี้พิมพ์ activity เป็นตัวใหญ่ ('6SP') แต่ catalog
--   ประกอบเป็นตัวเล็ก ('6sp') — ที่นี่เก็บตามรูปแบบ catalog เพื่อ join เอาชื่อไทยได้ตรง
--
-- idempotent: ON CONFLICT DO UPDATE ทั้งหมด — รันซ้ำได้ปลอดภัย
-- หมายเหตุ: ปรับชื่อ/ประเภท/ที่อยู่/เบอร์โทรได้จากหน้า Customers ในระบบ
--           (ไฟล์ต้นทางมีแค่ชื่อลูกค้า ไม่มีข้อมูลติดต่อ)

-- ===== 1) VAT ต่อลูกค้า =====
-- ลูกค้า 4 รายในชุดข้อมูลนี้ออกบิลแบบไม่มี VAT (Loft Space, Nadda Pool Villa,
-- บ้านหญ้าหมู, รัตนสิน โฮเทล) จึงต้องเก็บอัตราภาษีไว้ที่ระดับลูกค้า
ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS vat_rate NUMERIC(6,4) NOT NULL DEFAULT 0.07;

COMMENT ON COLUMN customers.vat_rate IS 'อัตรา VAT ของลูกค้ารายนี้ (เศษส่วน เช่น 0.07 = 7%, 0 = ไม่คิด VAT)';

-- ===== 2) ตารางราคาต่อลูกค้า =====
DO $$ BEGIN
  CREATE TYPE price_service_type AS ENUM (
    'wash',    -- ค่าซัก (ผ้าลูกค้าเอง / COG)
    'rental'   -- ค่าเช่าผ้า (ผ้าของโรงซัก)
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS customer_price_lists (
  id            VARCHAR(80) PRIMARY KEY,
  customer_id   VARCHAR(50) NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  sku           VARCHAR(20) NOT NULL,   -- รหัสเต็มตามรูปแบบ v_sku_catalog เช่น '6sp', 'A01L'
  product_code  VARCHAR(10) NOT NULL REFERENCES catalog_products(code),
  size_code     VARCHAR(10) NOT NULL DEFAULT '' REFERENCES catalog_sizes(code),
  activity_code VARCHAR(10) NOT NULL DEFAULT '' REFERENCES catalog_activities(code),
  service_type  price_service_type NOT NULL DEFAULT 'wash',
  unit_price    NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
  is_active     BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ DEFAULT now(),
  updated_at    TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT customer_price_lists_uniq UNIQUE (customer_id, sku, service_type)
);

CREATE INDEX IF NOT EXISTS idx_cpl_customer ON customer_price_lists(customer_id);
CREATE INDEX IF NOT EXISTS idx_cpl_sku ON customer_price_lists(sku);

DROP TRIGGER IF EXISTS update_customer_price_lists_updated_at ON customer_price_lists;
CREATE TRIGGER update_customer_price_lists_updated_at BEFORE UPDATE ON customer_price_lists
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ===== 3) ลูกค้า 38 ราย (สาขา LaundryKing = branch-1) =====
INSERT INTO customers (id, name, customer_type, branch_id, vat_rate, is_active) VALUES
  ('cust-a-day-inn', 'A Day Inn', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-baan-chino', 'บ้านชิโน', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-baan-choeng-khao', 'บ้านเชิงเขา', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-baan-ya-moo', 'บ้านหญ้าหมู', 'hotel'::customer_type, 'branch-1', 0, true),
  ('cust-blu-monkey', 'Blu Monkey', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-daddys-dream', 'Daddy''s Dream', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-farmhouse', 'ฟาร์มเฮ้าส์', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-farmhouse-new', 'ฟาร์มเฮ้าส์ (ตึกใหม่)', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-greenish', 'Greenish', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-khun-jim', 'คุณจิ๋ม', 'individual'::customer_type, 'branch-1', 0.07, true),
  ('cust-khun-natt', 'Khun Natt', 'individual'::customer_type, 'branch-1', 0.07, true),
  ('cust-khun-sin', 'คุณซิน', 'individual'::customer_type, 'branch-1', 0.07, true),
  ('cust-kiang-le', 'เคียงเล', 'restaurant'::customer_type, 'branch-1', 0.07, true),
  ('cust-le-nong', 'เลอนอง', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-loft-space', 'Loft Space', 'hotel'::customer_type, 'branch-1', 0, true),
  ('cust-mani', 'MANI', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-momda', 'Momda', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-mrs-swan-villas', 'Mrs.Swan Villas', 'resort'::customer_type, 'branch-1', 0.07, true),
  ('cust-nadda-pool-villa', 'Nadda Pool Villa', 'resort'::customer_type, 'branch-1', 0, true),
  ('cust-namsai-khaosuay', 'น้ำใสเขาสวย รีสอร์ท', 'resort'::customer_type, 'branch-1', 0.07, true),
  ('cust-pinthira-resort', 'พิณทิรา รีสอร์ท', 'resort'::customer_type, 'branch-1', 0.07, true),
  ('cust-raenong-boutique', 'แร่นองบูติค', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-rak-ranong', 'RAK Ranong', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-rattanasin-hotel', 'รัตนสิน โฮเทล', 'hotel'::customer_type, 'branch-1', 0, true),
  ('cust-rph-ranong-mri', 'รพ.ระนอง (MRI)', 'hospital'::customer_type, 'branch-1', 0.07, true),
  ('cust-ruangrat-hotel', 'เรืองราษฎร์ โฮเทล', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-ssru', 'ราชภัฏสวนสุนันทา', 'other'::customer_type, 'branch-1', 0.07, true),
  ('cust-st-park', 'S.T.Park', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-suk-hotel', 'สุขโฮเทล', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-sunnyvale', 'Sunnyvale', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-than-sila', 'ธารศิลา', 'resort'::customer_type, 'branch-1', 0.07, true),
  ('cust-the-crest', 'เดอะ เครสท์', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-the-ele', 'The ele', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-the-galla', 'The Galla', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-the-iconic-hotel', 'THE ICONIC HOTEL', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-the-white-village', 'The White Village', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-tobedzz', 'TOBEDzZ', 'hotel'::customer_type, 'branch-1', 0.07, true),
  ('cust-u-sabai', 'U sabai', 'hotel'::customer_type, 'branch-1', 0.07, true)
ON CONFLICT (id) DO UPDATE SET
  name          = EXCLUDED.name,
  customer_type = EXCLUDED.customer_type,
  branch_id     = EXCLUDED.branch_id,
  vat_rate      = EXCLUDED.vat_rate,
  updated_at    = now();

-- ===== 4) ราคาต่อลูกค้า (522 แถว: ค่าซัก 511 / ค่าเช่า 11) =====
INSERT INTO customer_price_lists
  (id, customer_id, sku, product_code, size_code, activity_code, service_type, unit_price) VALUES
  ('cpl-a-day-inn-wash-1', 'cust-a-day-inn', '1', '1', '', '', 'wash'::price_service_type, 9),
  ('cpl-a-day-inn-wash-12', 'cust-a-day-inn', '12', '12', '', '', 'wash'::price_service_type, 42),
  ('cpl-a-day-inn-wash-13', 'cust-a-day-inn', '13', '13', '', '', 'wash'::price_service_type, 37),
  ('cpl-a-day-inn-wash-4', 'cust-a-day-inn', '4', '4', '', '', 'wash'::price_service_type, 7),
  ('cpl-a-day-inn-wash-5', 'cust-a-day-inn', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-a-day-inn-wash-6d', 'cust-a-day-inn', '6d', '6', '', 'd', 'wash'::price_service_type, 13),
  ('cpl-a-day-inn-wash-7d', 'cust-a-day-inn', '7d', '7', '', 'd', 'wash'::price_service_type, 11),
  ('cpl-a-day-inn-wash-8d', 'cust-a-day-inn', '8d', '8', '', 'd', 'wash'::price_service_type, 15),
  ('cpl-a-day-inn-wash-a02', 'cust-a-day-inn', 'A02', 'A02', '', '', 'wash'::price_service_type, 19),
  ('cpl-baan-chino-wash-1', 'cust-baan-chino', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-baan-chino-wash-3', 'cust-baan-chino', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-baan-chino-wash-4', 'cust-baan-chino', '4', '4', '', '', 'wash'::price_service_type, 8),
  ('cpl-baan-chino-wash-5', 'cust-baan-chino', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-baan-chino-wash-6', 'cust-baan-chino', '6', '6', '', '', 'wash'::price_service_type, 28),
  ('cpl-baan-chino-wash-7', 'cust-baan-chino', '7', '7', '', '', 'wash'::price_service_type, 23),
  ('cpl-baan-chino-wash-8', 'cust-baan-chino', '8', '8', '', '', 'wash'::price_service_type, 33),
  ('cpl-baan-chino-wash-9', 'cust-baan-chino', '9', '9', '', '', 'wash'::price_service_type, 28),
  ('cpl-baan-choeng-khao-wash-1', 'cust-baan-choeng-khao', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-baan-choeng-khao-wash-13', 'cust-baan-choeng-khao', '13', '13', '', '', 'wash'::price_service_type, 40),
  ('cpl-baan-choeng-khao-wash-1sp', 'cust-baan-choeng-khao', '1sp', '1', '', 'sp', 'wash'::price_service_type, 15),
  ('cpl-baan-choeng-khao-wash-3', 'cust-baan-choeng-khao', '3', '3', '', '', 'wash'::price_service_type, 4),
  ('cpl-baan-choeng-khao-wash-3sp', 'cust-baan-choeng-khao', '3sp', '3', '', 'sp', 'wash'::price_service_type, 6),
  ('cpl-baan-choeng-khao-wash-6', 'cust-baan-choeng-khao', '6', '6', '', '', 'wash'::price_service_type, 28),
  ('cpl-baan-choeng-khao-wash-7', 'cust-baan-choeng-khao', '7', '7', '', '', 'wash'::price_service_type, 23),
  ('cpl-baan-choeng-khao-wash-8', 'cust-baan-choeng-khao', '8', '8', '', '', 'wash'::price_service_type, 33),
  ('cpl-baan-choeng-khao-wash-9', 'cust-baan-choeng-khao', '9', '9', '', '', 'wash'::price_service_type, 28),
  ('cpl-baan-choeng-khao-wash-a01l', 'cust-baan-choeng-khao', 'A01L', 'A01', 'L', '', 'wash'::price_service_type, 70),
  ('cpl-baan-ya-moo-wash-1', 'cust-baan-ya-moo', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-baan-ya-moo-wash-14', 'cust-baan-ya-moo', '14', '14', '', '', 'wash'::price_service_type, 8),
  ('cpl-baan-ya-moo-wash-3', 'cust-baan-ya-moo', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-baan-ya-moo-wash-3sp', 'cust-baan-ya-moo', '3sp', '3', '', 'sp', 'wash'::price_service_type, 10),
  ('cpl-baan-ya-moo-wash-4', 'cust-baan-ya-moo', '4', '4', '', '', 'wash'::price_service_type, 8),
  ('cpl-baan-ya-moo-wash-5', 'cust-baan-ya-moo', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-baan-ya-moo-wash-6', 'cust-baan-ya-moo', '6', '6', '', '', 'wash'::price_service_type, 28),
  ('cpl-baan-ya-moo-wash-6sp', 'cust-baan-ya-moo', '6sp', '6', '', 'sp', 'wash'::price_service_type, 56),
  ('cpl-baan-ya-moo-wash-7', 'cust-baan-ya-moo', '7', '7', '', '', 'wash'::price_service_type, 23),
  ('cpl-baan-ya-moo-wash-8', 'cust-baan-ya-moo', '8', '8', '', '', 'wash'::price_service_type, 33),
  ('cpl-baan-ya-moo-wash-8sp', 'cust-baan-ya-moo', '8sp', '8', '', 'sp', 'wash'::price_service_type, 66),
  ('cpl-baan-ya-moo-wash-9', 'cust-baan-ya-moo', '9', '9', '', '', 'wash'::price_service_type, 28),
  ('cpl-baan-ya-moo-wash-9sp', 'cust-baan-ya-moo', '9sp', '9', '', 'sp', 'wash'::price_service_type, 42),
  ('cpl-baan-ya-moo-wash-a15', 'cust-baan-ya-moo', 'A15', 'A15', '', '', 'wash'::price_service_type, 25),
  ('cpl-blu-monkey-wash-1', 'cust-blu-monkey', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-blu-monkey-wash-12', 'cust-blu-monkey', '12', '12', '', '', 'wash'::price_service_type, 45),
  ('cpl-blu-monkey-wash-12sp', 'cust-blu-monkey', '12sp', '12', '', 'sp', 'wash'::price_service_type, 68),
  ('cpl-blu-monkey-wash-13', 'cust-blu-monkey', '13', '13', '', '', 'wash'::price_service_type, 45),
  ('cpl-blu-monkey-wash-13sp', 'cust-blu-monkey', '13sp', '13', '', 'sp', 'wash'::price_service_type, 68),
  ('cpl-blu-monkey-wash-1sp', 'cust-blu-monkey', '1sp', '1', '', 'sp', 'wash'::price_service_type, 15),
  ('cpl-blu-monkey-wash-3', 'cust-blu-monkey', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-blu-monkey-wash-3sp', 'cust-blu-monkey', '3sp', '3', '', 'sp', 'wash'::price_service_type, 8),
  ('cpl-blu-monkey-wash-4', 'cust-blu-monkey', '4', '4', '', '', 'wash'::price_service_type, 7),
  ('cpl-blu-monkey-wash-4sp', 'cust-blu-monkey', '4sp', '4', '', 'sp', 'wash'::price_service_type, 11),
  ('cpl-blu-monkey-wash-5', 'cust-blu-monkey', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-blu-monkey-wash-6', 'cust-blu-monkey', '6', '6', '', '', 'wash'::price_service_type, 25),
  ('cpl-blu-monkey-wash-7', 'cust-blu-monkey', '7', '7', '', '', 'wash'::price_service_type, 20),
  ('cpl-blu-monkey-wash-8', 'cust-blu-monkey', '8', '8', '', '', 'wash'::price_service_type, 30),
  ('cpl-blu-monkey-wash-9', 'cust-blu-monkey', '9', '9', '', '', 'wash'::price_service_type, 25),
  ('cpl-blu-monkey-wash-a01s', 'cust-blu-monkey', 'A01S', 'A01', 'S', '', 'wash'::price_service_type, 60),
  ('cpl-blu-monkey-wash-a04sp', 'cust-blu-monkey', 'A04sp', 'A04', '', 'sp', 'wash'::price_service_type, 15),
  ('cpl-blu-monkey-wash-a13lsp', 'cust-blu-monkey', 'A13Lsp', 'A13', 'L', 'sp', 'wash'::price_service_type, 225),
  ('cpl-daddys-dream-wash-1', 'cust-daddys-dream', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-daddys-dream-wash-16', 'cust-daddys-dream', '16', '16', '', '', 'wash'::price_service_type, 10),
  ('cpl-daddys-dream-wash-17', 'cust-daddys-dream', '17', '17', '', '', 'wash'::price_service_type, 5),
  ('cpl-daddys-dream-wash-17sp', 'cust-daddys-dream', '17sp', '17', '', 'sp', 'wash'::price_service_type, 8),
  ('cpl-daddys-dream-wash-18', 'cust-daddys-dream', '18', '18', '', '', 'wash'::price_service_type, 40),
  ('cpl-daddys-dream-wash-1sp', 'cust-daddys-dream', '1sp', '1', '', 'sp', 'wash'::price_service_type, 15),
  ('cpl-daddys-dream-wash-3', 'cust-daddys-dream', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-daddys-dream-wash-3sp', 'cust-daddys-dream', '3sp', '3', '', 'sp', 'wash'::price_service_type, 8),
  ('cpl-daddys-dream-wash-4', 'cust-daddys-dream', '4', '4', '', '', 'wash'::price_service_type, 7),
  ('cpl-daddys-dream-wash-5', 'cust-daddys-dream', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-daddys-dream-wash-6', 'cust-daddys-dream', '6', '6', '', '', 'wash'::price_service_type, 30),
  ('cpl-daddys-dream-wash-7', 'cust-daddys-dream', '7', '7', '', '', 'wash'::price_service_type, 25),
  ('cpl-daddys-dream-wash-8', 'cust-daddys-dream', '8', '8', '', '', 'wash'::price_service_type, 35),
  ('cpl-daddys-dream-wash-9', 'cust-daddys-dream', '9', '9', '', '', 'wash'::price_service_type, 30),
  ('cpl-daddys-dream-wash-a01l', 'cust-daddys-dream', 'A01L', 'A01', 'L', '', 'wash'::price_service_type, 60),
  ('cpl-daddys-dream-wash-a02', 'cust-daddys-dream', 'A02', 'A02', '', '', 'wash'::price_service_type, 30),
  ('cpl-daddys-dream-wash-a09', 'cust-daddys-dream', 'A09', 'A09', '', '', 'wash'::price_service_type, 60),
  ('cpl-daddys-dream-wash-a18', 'cust-daddys-dream', 'A18', 'A18', '', '', 'wash'::price_service_type, 50),
  ('cpl-daddys-dream-wash-a31', 'cust-daddys-dream', 'A31', 'A31', '', '', 'wash'::price_service_type, 15),
  ('cpl-farmhouse-wash-1', 'cust-farmhouse', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-farmhouse-wash-12', 'cust-farmhouse', '12', '12', '', '', 'wash'::price_service_type, 45),
  ('cpl-farmhouse-wash-12sp', 'cust-farmhouse', '12sp', '12', '', 'sp', 'wash'::price_service_type, 90),
  ('cpl-farmhouse-wash-13', 'cust-farmhouse', '13', '13', '', '', 'wash'::price_service_type, 45),
  ('cpl-farmhouse-wash-18', 'cust-farmhouse', '18', '18', '', '', 'wash'::price_service_type, 40),
  ('cpl-farmhouse-wash-3', 'cust-farmhouse', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-farmhouse-wash-4', 'cust-farmhouse', '4', '4', '', '', 'wash'::price_service_type, 8),
  ('cpl-farmhouse-wash-5', 'cust-farmhouse', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-farmhouse-wash-6', 'cust-farmhouse', '6', '6', '', '', 'wash'::price_service_type, 30),
  ('cpl-farmhouse-wash-6sp', 'cust-farmhouse', '6sp', '6', '', 'sp', 'wash'::price_service_type, 60),
  ('cpl-farmhouse-wash-7', 'cust-farmhouse', '7', '7', '', '', 'wash'::price_service_type, 25),
  ('cpl-farmhouse-wash-8', 'cust-farmhouse', '8', '8', '', '', 'wash'::price_service_type, 33),
  ('cpl-farmhouse-wash-9', 'cust-farmhouse', '9', '9', '', '', 'wash'::price_service_type, 30),
  ('cpl-farmhouse-wash-a01l', 'cust-farmhouse', 'A01L', 'A01', 'L', '', 'wash'::price_service_type, 70),
  ('cpl-farmhouse-wash-a01s', 'cust-farmhouse', 'A01S', 'A01', 'S', '', 'wash'::price_service_type, 70),
  ('cpl-farmhouse-wash-a04', 'cust-farmhouse', 'A04', 'A04', '', '', 'wash'::price_service_type, 10),
  ('cpl-farmhouse-wash-a09', 'cust-farmhouse', 'A09', 'A09', '', '', 'wash'::price_service_type, 30),
  ('cpl-farmhouse-wash-a13s', 'cust-farmhouse', 'A13S', 'A13', 'S', '', 'wash'::price_service_type, 150),
  ('cpl-farmhouse-wash-a13ssp', 'cust-farmhouse', 'A13Ssp', 'A13', 'S', 'sp', 'wash'::price_service_type, 300),
  ('cpl-farmhouse-rental-r3', 'cust-farmhouse', 'R3', 'R3', '', '', 'rental'::price_service_type, 7),
  ('cpl-farmhouse-rental-r6l', 'cust-farmhouse', 'R6L', 'R6L', '', '', 'rental'::price_service_type, 39),
  ('cpl-farmhouse-rental-r7', 'cust-farmhouse', 'R7', 'R7', '', '', 'rental'::price_service_type, 30),
  ('cpl-farmhouse-new-wash-1', 'cust-farmhouse-new', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-farmhouse-new-wash-12', 'cust-farmhouse-new', '12', '12', '', '', 'wash'::price_service_type, 45),
  ('cpl-farmhouse-new-wash-12sp', 'cust-farmhouse-new', '12sp', '12', '', 'sp', 'wash'::price_service_type, 68),
  ('cpl-farmhouse-new-wash-13', 'cust-farmhouse-new', '13', '13', '', '', 'wash'::price_service_type, 45),
  ('cpl-farmhouse-new-wash-14', 'cust-farmhouse-new', '14', '14', '', '', 'wash'::price_service_type, 10),
  ('cpl-farmhouse-new-wash-18', 'cust-farmhouse-new', '18', '18', '', '', 'wash'::price_service_type, 40),
  ('cpl-farmhouse-new-wash-19', 'cust-farmhouse-new', '19', '19', '', '', 'wash'::price_service_type, 50),
  ('cpl-farmhouse-new-wash-2', 'cust-farmhouse-new', '2', '2', '', '', 'wash'::price_service_type, 5),
  ('cpl-farmhouse-new-wash-20', 'cust-farmhouse-new', '20', '20', '', '', 'wash'::price_service_type, 80),
  ('cpl-farmhouse-new-wash-21', 'cust-farmhouse-new', '21', '21', '', '', 'wash'::price_service_type, 15),
  ('cpl-farmhouse-new-wash-3', 'cust-farmhouse-new', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-farmhouse-new-wash-4', 'cust-farmhouse-new', '4', '4', '', '', 'wash'::price_service_type, 8),
  ('cpl-farmhouse-new-wash-5', 'cust-farmhouse-new', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-farmhouse-new-wash-6', 'cust-farmhouse-new', '6', '6', '', '', 'wash'::price_service_type, 30),
  ('cpl-farmhouse-new-wash-7', 'cust-farmhouse-new', '7', '7', '', '', 'wash'::price_service_type, 25),
  ('cpl-farmhouse-new-wash-8', 'cust-farmhouse-new', '8', '8', '', '', 'wash'::price_service_type, 33),
  ('cpl-farmhouse-new-wash-9', 'cust-farmhouse-new', '9', '9', '', '', 'wash'::price_service_type, 30),
  ('cpl-farmhouse-new-wash-a01l', 'cust-farmhouse-new', 'A01L', 'A01', 'L', '', 'wash'::price_service_type, 70),
  ('cpl-farmhouse-new-wash-a01s', 'cust-farmhouse-new', 'A01S', 'A01', 'S', '', 'wash'::price_service_type, 70),
  ('cpl-farmhouse-new-wash-a04', 'cust-farmhouse-new', 'A04', 'A04', '', '', 'wash'::price_service_type, 10),
  ('cpl-farmhouse-new-wash-a13ssp', 'cust-farmhouse-new', 'A13Ssp', 'A13', 'S', 'sp', 'wash'::price_service_type, 225),
  ('cpl-farmhouse-new-rental-r1', 'cust-farmhouse-new', 'R1', 'R1', '', '', 'rental'::price_service_type, 15),
  ('cpl-farmhouse-new-rental-r3', 'cust-farmhouse-new', 'R3', 'R3', '', '', 'rental'::price_service_type, 7),
  ('cpl-farmhouse-new-rental-r6l', 'cust-farmhouse-new', 'R6L', 'R6L', '', '', 'rental'::price_service_type, 39),
  ('cpl-farmhouse-new-rental-r7', 'cust-farmhouse-new', 'R7', 'R7', '', '', 'rental'::price_service_type, 30),
  ('cpl-greenish-wash-1', 'cust-greenish', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-greenish-wash-12', 'cust-greenish', '12', '12', '', '', 'wash'::price_service_type, 45),
  ('cpl-greenish-wash-1sp', 'cust-greenish', '1sp', '1', '', 'sp', 'wash'::price_service_type, 15),
  ('cpl-greenish-wash-3', 'cust-greenish', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-greenish-wash-3sp', 'cust-greenish', '3sp', '3', '', 'sp', 'wash'::price_service_type, 8),
  ('cpl-greenish-wash-4', 'cust-greenish', '4', '4', '', '', 'wash'::price_service_type, 8),
  ('cpl-greenish-wash-5', 'cust-greenish', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-greenish-wash-6', 'cust-greenish', '6', '6', '', '', 'wash'::price_service_type, 28),
  ('cpl-greenish-wash-7', 'cust-greenish', '7', '7', '', '', 'wash'::price_service_type, 23),
  ('cpl-greenish-wash-8', 'cust-greenish', '8', '8', '', '', 'wash'::price_service_type, 33),
  ('cpl-greenish-wash-9', 'cust-greenish', '9', '9', '', '', 'wash'::price_service_type, 28),
  ('cpl-khun-jim-wash-1', 'cust-khun-jim', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-khun-jim-wash-10', 'cust-khun-jim', '10', '10', '', '', 'wash'::price_service_type, 70),
  ('cpl-khun-jim-wash-10c', 'cust-khun-jim', '10C', '10', 'C', '', 'wash'::price_service_type, 70),
  ('cpl-khun-jim-wash-11', 'cust-khun-jim', '11', '11', '', '', 'wash'::price_service_type, 60),
  ('cpl-khun-jim-wash-11c', 'cust-khun-jim', '11C', '11', 'C', '', 'wash'::price_service_type, 60),
  ('cpl-khun-jim-wash-17', 'cust-khun-jim', '17', '17', '', '', 'wash'::price_service_type, 5),
  ('cpl-khun-jim-wash-1c', 'cust-khun-jim', '1C', '1', 'C', '', 'wash'::price_service_type, 10),
  ('cpl-khun-jim-wash-3', 'cust-khun-jim', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-khun-jim-wash-3sp', 'cust-khun-jim', '3sp', '3', '', 'sp', 'wash'::price_service_type, 8),
  ('cpl-khun-jim-wash-5c', 'cust-khun-jim', '5C', '5', 'C', '', 'wash'::price_service_type, 5),
  ('cpl-khun-jim-wash-5sp', 'cust-khun-jim', '5sp', '5', '', 'sp', 'wash'::price_service_type, 8),
  ('cpl-khun-jim-wash-6', 'cust-khun-jim', '6', '6', '', '', 'wash'::price_service_type, 25),
  ('cpl-khun-jim-wash-6c', 'cust-khun-jim', '6C', '6', 'C', '', 'wash'::price_service_type, 25),
  ('cpl-khun-jim-wash-7', 'cust-khun-jim', '7', '7', '', '', 'wash'::price_service_type, 20),
  ('cpl-khun-jim-wash-7c', 'cust-khun-jim', '7C', '7', 'C', '', 'wash'::price_service_type, 20),
  ('cpl-khun-jim-wash-a01l', 'cust-khun-jim', 'A01L', 'A01', 'L', '', 'wash'::price_service_type, 70),
  ('cpl-khun-jim-wash-a01s', 'cust-khun-jim', 'A01S', 'A01', 'S', '', 'wash'::price_service_type, 60),
  ('cpl-khun-natt-wash-1', 'cust-khun-natt', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-khun-natt-wash-3', 'cust-khun-natt', '3', '3', '', '', 'wash'::price_service_type, 4),
  ('cpl-khun-natt-wash-4', 'cust-khun-natt', '4', '4', '', '', 'wash'::price_service_type, 8),
  ('cpl-khun-natt-wash-5', 'cust-khun-natt', '5', '5', '', '', 'wash'::price_service_type, 6),
  ('cpl-khun-natt-wash-6', 'cust-khun-natt', '6', '6', '', '', 'wash'::price_service_type, 28),
  ('cpl-khun-natt-wash-7', 'cust-khun-natt', '7', '7', '', '', 'wash'::price_service_type, 23),
  ('cpl-khun-natt-wash-8', 'cust-khun-natt', '8', '8', '', '', 'wash'::price_service_type, 33),
  ('cpl-khun-natt-wash-9', 'cust-khun-natt', '9', '9', '', '', 'wash'::price_service_type, 28),
  ('cpl-khun-sin-wash-1', 'cust-khun-sin', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-khun-sin-wash-3', 'cust-khun-sin', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-khun-sin-wash-5', 'cust-khun-sin', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-khun-sin-wash-6', 'cust-khun-sin', '6', '6', '', '', 'wash'::price_service_type, 28),
  ('cpl-khun-sin-wash-7', 'cust-khun-sin', '7', '7', '', '', 'wash'::price_service_type, 23),
  ('cpl-khun-sin-wash-8', 'cust-khun-sin', '8', '8', '', '', 'wash'::price_service_type, 33),
  ('cpl-khun-sin-wash-9', 'cust-khun-sin', '9', '9', '', '', 'wash'::price_service_type, 28),
  ('cpl-kiang-le-wash-21', 'cust-kiang-le', '21', '21', '', '', 'wash'::price_service_type, 12),
  ('cpl-kiang-le-wash-21m', 'cust-kiang-le', '21M', '21', 'M', '', 'wash'::price_service_type, 30),
  ('cpl-kiang-le-wash-22', 'cust-kiang-le', '22', '22', '', '', 'wash'::price_service_type, 3),
  ('cpl-kiang-le-wash-23', 'cust-kiang-le', '23', '23', '', '', 'wash'::price_service_type, 35),
  ('cpl-le-nong-wash-1', 'cust-le-nong', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-le-nong-wash-12', 'cust-le-nong', '12', '12', '', '', 'wash'::price_service_type, 45),
  ('cpl-le-nong-wash-3', 'cust-le-nong', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-le-nong-wash-3sp', 'cust-le-nong', '3sp', '3', '', 'sp', 'wash'::price_service_type, 8),
  ('cpl-le-nong-wash-4', 'cust-le-nong', '4', '4', '', '', 'wash'::price_service_type, 7),
  ('cpl-le-nong-wash-4sp', 'cust-le-nong', '4sp', '4', '', 'sp', 'wash'::price_service_type, 11),
  ('cpl-le-nong-wash-5', 'cust-le-nong', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-le-nong-wash-6', 'cust-le-nong', '6', '6', '', '', 'wash'::price_service_type, 25),
  ('cpl-le-nong-wash-7', 'cust-le-nong', '7', '7', '', '', 'wash'::price_service_type, 20),
  ('cpl-le-nong-wash-8', 'cust-le-nong', '8', '8', '', '', 'wash'::price_service_type, 30),
  ('cpl-le-nong-wash-9', 'cust-le-nong', '9', '9', '', '', 'wash'::price_service_type, 25),
  ('cpl-loft-space-wash-1', 'cust-loft-space', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-loft-space-wash-1sp', 'cust-loft-space', '1sp', '1', '', 'sp', 'wash'::price_service_type, 15),
  ('cpl-loft-space-wash-4', 'cust-loft-space', '4', '4', '', '', 'wash'::price_service_type, 8),
  ('cpl-loft-space-wash-5', 'cust-loft-space', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-loft-space-wash-6', 'cust-loft-space', '6', '6', '', '', 'wash'::price_service_type, 28),
  ('cpl-loft-space-wash-7', 'cust-loft-space', '7', '7', '', '', 'wash'::price_service_type, 23),
  ('cpl-loft-space-wash-8', 'cust-loft-space', '8', '8', '', '', 'wash'::price_service_type, 33),
  ('cpl-loft-space-wash-9', 'cust-loft-space', '9', '9', '', '', 'wash'::price_service_type, 28),
  ('cpl-mani-wash-1', 'cust-mani', '1', '1', '', '', 'wash'::price_service_type, 9),
  ('cpl-mani-wash-12', 'cust-mani', '12', '12', '', '', 'wash'::price_service_type, 45),
  ('cpl-mani-wash-13', 'cust-mani', '13', '13', '', '', 'wash'::price_service_type, 45),
  ('cpl-mani-wash-3', 'cust-mani', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-mani-wash-4', 'cust-mani', '4', '4', '', '', 'wash'::price_service_type, 7),
  ('cpl-mani-wash-5', 'cust-mani', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-mani-wash-6', 'cust-mani', '6', '6', '', '', 'wash'::price_service_type, 25),
  ('cpl-mani-wash-7', 'cust-mani', '7', '7', '', '', 'wash'::price_service_type, 20),
  ('cpl-mani-wash-7sp', 'cust-mani', '7sp', '7', '', 'sp', 'wash'::price_service_type, 30),
  ('cpl-mani-wash-8', 'cust-mani', '8', '8', '', '', 'wash'::price_service_type, 30),
  ('cpl-mani-wash-9', 'cust-mani', '9', '9', '', '', 'wash'::price_service_type, 25),
  ('cpl-mani-wash-a01l', 'cust-mani', 'A01L', 'A01', 'L', '', 'wash'::price_service_type, 70),
  ('cpl-mani-wash-a04', 'cust-mani', 'A04', 'A04', '', '', 'wash'::price_service_type, 10),
  ('cpl-mani-wash-a13s', 'cust-mani', 'A13S', 'A13', 'S', '', 'wash'::price_service_type, 120),
  ('cpl-momda-wash-1', 'cust-momda', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-momda-wash-3', 'cust-momda', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-momda-wash-4', 'cust-momda', '4', '4', '', '', 'wash'::price_service_type, 8),
  ('cpl-momda-wash-5', 'cust-momda', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-momda-wash-6', 'cust-momda', '6', '6', '', '', 'wash'::price_service_type, 28),
  ('cpl-momda-wash-7', 'cust-momda', '7', '7', '', '', 'wash'::price_service_type, 23),
  ('cpl-momda-wash-8', 'cust-momda', '8', '8', '', '', 'wash'::price_service_type, 33),
  ('cpl-momda-wash-9', 'cust-momda', '9', '9', '', '', 'wash'::price_service_type, 28),
  ('cpl-mrs-swan-villas-wash-1', 'cust-mrs-swan-villas', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-mrs-swan-villas-wash-12', 'cust-mrs-swan-villas', '12', '12', '', '', 'wash'::price_service_type, 40),
  ('cpl-mrs-swan-villas-wash-13', 'cust-mrs-swan-villas', '13', '13', '', '', 'wash'::price_service_type, 40),
  ('cpl-mrs-swan-villas-wash-14', 'cust-mrs-swan-villas', '14', '14', '', '', 'wash'::price_service_type, 10),
  ('cpl-mrs-swan-villas-wash-16', 'cust-mrs-swan-villas', '16', '16', '', '', 'wash'::price_service_type, 10),
  ('cpl-mrs-swan-villas-wash-17', 'cust-mrs-swan-villas', '17', '17', '', '', 'wash'::price_service_type, 4),
  ('cpl-mrs-swan-villas-wash-19', 'cust-mrs-swan-villas', '19', '19', '', '', 'wash'::price_service_type, 40),
  ('cpl-mrs-swan-villas-wash-2', 'cust-mrs-swan-villas', '2', '2', '', '', 'wash'::price_service_type, 3),
  ('cpl-mrs-swan-villas-wash-20', 'cust-mrs-swan-villas', '20', '20', '', '', 'wash'::price_service_type, 120),
  ('cpl-mrs-swan-villas-wash-3', 'cust-mrs-swan-villas', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-mrs-swan-villas-wash-4', 'cust-mrs-swan-villas', '4', '4', '', '', 'wash'::price_service_type, 7),
  ('cpl-mrs-swan-villas-wash-5', 'cust-mrs-swan-villas', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-mrs-swan-villas-wash-6', 'cust-mrs-swan-villas', '6', '6', '', '', 'wash'::price_service_type, 30),
  ('cpl-mrs-swan-villas-wash-7', 'cust-mrs-swan-villas', '7', '7', '', '', 'wash'::price_service_type, 25),
  ('cpl-mrs-swan-villas-wash-8', 'cust-mrs-swan-villas', '8', '8', '', '', 'wash'::price_service_type, 35),
  ('cpl-mrs-swan-villas-wash-9', 'cust-mrs-swan-villas', '9', '9', '', '', 'wash'::price_service_type, 30),
  ('cpl-mrs-swan-villas-wash-a04', 'cust-mrs-swan-villas', 'A04', 'A04', '', '', 'wash'::price_service_type, 10),
  ('cpl-mrs-swan-villas-wash-a14', 'cust-mrs-swan-villas', 'A14', 'A14', '', '', 'wash'::price_service_type, 15),
  ('cpl-mrs-swan-villas-wash-a21', 'cust-mrs-swan-villas', 'A21', 'A21', '', '', 'wash'::price_service_type, 6),
  ('cpl-mrs-swan-villas-wash-a28', 'cust-mrs-swan-villas', 'A28', 'A28', '', '', 'wash'::price_service_type, 15),
  ('cpl-mrs-swan-villas-wash-a41', 'cust-mrs-swan-villas', 'A41', 'A41', '', '', 'wash'::price_service_type, 50),
  ('cpl-mrs-swan-villas-wash-a44', 'cust-mrs-swan-villas', 'A44', 'A44', '', '', 'wash'::price_service_type, 50),
  ('cpl-mrs-swan-villas-wash-a46', 'cust-mrs-swan-villas', 'A46', 'A46', '', '', 'wash'::price_service_type, 5),
  ('cpl-mrs-swan-villas-rental-r3', 'cust-mrs-swan-villas', 'R3', 'R3', '', '', 'rental'::price_service_type, 7),
  ('cpl-mrs-swan-villas-rental-r4', 'cust-mrs-swan-villas', 'R4', 'R4', '', '', 'rental'::price_service_type, 11),
  ('cpl-mrs-swan-villas-rental-r5l', 'cust-mrs-swan-villas', 'R5L', 'R5L', '', '', 'rental'::price_service_type, 8),
  ('cpl-mrs-swan-villas-rental-r7', 'cust-mrs-swan-villas', 'R7', 'R7', '', '', 'rental'::price_service_type, 40),
  ('cpl-nadda-pool-villa-wash-1', 'cust-nadda-pool-villa', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-nadda-pool-villa-wash-4', 'cust-nadda-pool-villa', '4', '4', '', '', 'wash'::price_service_type, 7),
  ('cpl-nadda-pool-villa-wash-5', 'cust-nadda-pool-villa', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-nadda-pool-villa-wash-6', 'cust-nadda-pool-villa', '6', '6', '', '', 'wash'::price_service_type, 25),
  ('cpl-nadda-pool-villa-wash-7', 'cust-nadda-pool-villa', '7', '7', '', '', 'wash'::price_service_type, 20),
  ('cpl-nadda-pool-villa-wash-8', 'cust-nadda-pool-villa', '8', '8', '', '', 'wash'::price_service_type, 30),
  ('cpl-namsai-khaosuay-wash-1', 'cust-namsai-khaosuay', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-namsai-khaosuay-wash-12sp', 'cust-namsai-khaosuay', '12sp', '12', '', 'sp', 'wash'::price_service_type, 50),
  ('cpl-namsai-khaosuay-wash-13', 'cust-namsai-khaosuay', '13', '13', '', '', 'wash'::price_service_type, 35),
  ('cpl-namsai-khaosuay-wash-14', 'cust-namsai-khaosuay', '14', '14', '', '', 'wash'::price_service_type, 10),
  ('cpl-namsai-khaosuay-wash-16', 'cust-namsai-khaosuay', '16', '16', '', '', 'wash'::price_service_type, 10),
  ('cpl-namsai-khaosuay-wash-1sp', 'cust-namsai-khaosuay', '1sp', '1', '', 'sp', 'wash'::price_service_type, 15),
  ('cpl-namsai-khaosuay-wash-2', 'cust-namsai-khaosuay', '2', '2', '', '', 'wash'::price_service_type, 4),
  ('cpl-namsai-khaosuay-wash-21', 'cust-namsai-khaosuay', '21', '21', '', '', 'wash'::price_service_type, 20),
  ('cpl-namsai-khaosuay-wash-3', 'cust-namsai-khaosuay', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-namsai-khaosuay-wash-4', 'cust-namsai-khaosuay', '4', '4', '', '', 'wash'::price_service_type, 7),
  ('cpl-namsai-khaosuay-wash-5', 'cust-namsai-khaosuay', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-namsai-khaosuay-wash-6', 'cust-namsai-khaosuay', '6', '6', '', '', 'wash'::price_service_type, 30),
  ('cpl-namsai-khaosuay-wash-7', 'cust-namsai-khaosuay', '7', '7', '', '', 'wash'::price_service_type, 25),
  ('cpl-namsai-khaosuay-wash-8', 'cust-namsai-khaosuay', '8', '8', '', '', 'wash'::price_service_type, 35),
  ('cpl-namsai-khaosuay-wash-8sp', 'cust-namsai-khaosuay', '8sp', '8', '', 'sp', 'wash'::price_service_type, 53),
  ('cpl-namsai-khaosuay-wash-9', 'cust-namsai-khaosuay', '9', '9', '', '', 'wash'::price_service_type, 30),
  ('cpl-namsai-khaosuay-wash-a01s', 'cust-namsai-khaosuay', 'A01S', 'A01', 'S', '', 'wash'::price_service_type, 50),
  ('cpl-namsai-khaosuay-wash-a04', 'cust-namsai-khaosuay', 'A04', 'A04', '', '', 'wash'::price_service_type, 15),
  ('cpl-namsai-khaosuay-wash-a48', 'cust-namsai-khaosuay', 'A48', 'A48', '', '', 'wash'::price_service_type, 12),
  ('cpl-pinthira-resort-wash-1', 'cust-pinthira-resort', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-pinthira-resort-wash-10', 'cust-pinthira-resort', '10', '10', '', '', 'wash'::price_service_type, 70),
  ('cpl-pinthira-resort-wash-6', 'cust-pinthira-resort', '6', '6', '', '', 'wash'::price_service_type, 28),
  ('cpl-pinthira-resort-wash-7', 'cust-pinthira-resort', '7', '7', '', '', 'wash'::price_service_type, 23),
  ('cpl-pinthira-resort-wash-8', 'cust-pinthira-resort', '8', '8', '', '', 'wash'::price_service_type, 33),
  ('cpl-pinthira-resort-wash-a01l', 'cust-pinthira-resort', 'A01L', 'A01', 'L', '', 'wash'::price_service_type, 70),
  ('cpl-pinthira-resort-wash-a02', 'cust-pinthira-resort', 'A02', 'A02', '', '', 'wash'::price_service_type, 35),
  ('cpl-pinthira-resort-wash-a13s', 'cust-pinthira-resort', 'A13S', 'A13', 'S', '', 'wash'::price_service_type, 150),
  ('cpl-raenong-boutique-wash-1', 'cust-raenong-boutique', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-raenong-boutique-wash-17', 'cust-raenong-boutique', '17', '17', '', '', 'wash'::price_service_type, 4),
  ('cpl-raenong-boutique-wash-3', 'cust-raenong-boutique', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-raenong-boutique-wash-4', 'cust-raenong-boutique', '4', '4', '', '', 'wash'::price_service_type, 8),
  ('cpl-raenong-boutique-wash-5', 'cust-raenong-boutique', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-raenong-boutique-wash-6', 'cust-raenong-boutique', '6', '6', '', '', 'wash'::price_service_type, 28),
  ('cpl-raenong-boutique-wash-6sp', 'cust-raenong-boutique', '6sp', '6', '', 'sp', 'wash'::price_service_type, 42),
  ('cpl-raenong-boutique-wash-7', 'cust-raenong-boutique', '7', '7', '', '', 'wash'::price_service_type, 23),
  ('cpl-raenong-boutique-wash-8', 'cust-raenong-boutique', '8', '8', '', '', 'wash'::price_service_type, 33),
  ('cpl-raenong-boutique-wash-8sp', 'cust-raenong-boutique', '8sp', '8', '', 'sp', 'wash'::price_service_type, 50),
  ('cpl-raenong-boutique-wash-9', 'cust-raenong-boutique', '9', '9', '', '', 'wash'::price_service_type, 28),
  ('cpl-raenong-boutique-wash-a16', 'cust-raenong-boutique', 'A16', 'A16', '', '', 'wash'::price_service_type, 5),
  ('cpl-rak-ranong-wash-1', 'cust-rak-ranong', '1', '1', '', '', 'wash'::price_service_type, 9),
  ('cpl-rak-ranong-wash-1c', 'cust-rak-ranong', '1C', '1', 'C', '', 'wash'::price_service_type, 12),
  ('cpl-rak-ranong-wash-2sp', 'cust-rak-ranong', '2sp', '2', '', 'sp', 'wash'::price_service_type, 6),
  ('cpl-rak-ranong-wash-3', 'cust-rak-ranong', '3', '3', '', '', 'wash'::price_service_type, 4),
  ('cpl-rak-ranong-wash-3sp', 'cust-rak-ranong', '3sp', '3', '', 'sp', 'wash'::price_service_type, 6),
  ('cpl-rak-ranong-wash-4', 'cust-rak-ranong', '4', '4', '', '', 'wash'::price_service_type, 7),
  ('cpl-rak-ranong-wash-a02', 'cust-rak-ranong', 'A02', 'A02', '', '', 'wash'::price_service_type, 30),
  ('cpl-rattanasin-hotel-wash-1', 'cust-rattanasin-hotel', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-rattanasin-hotel-wash-2', 'cust-rattanasin-hotel', '2', '2', '', '', 'wash'::price_service_type, 4),
  ('cpl-rattanasin-hotel-wash-3', 'cust-rattanasin-hotel', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-rattanasin-hotel-wash-4', 'cust-rattanasin-hotel', '4', '4', '', '', 'wash'::price_service_type, 8),
  ('cpl-rattanasin-hotel-wash-5', 'cust-rattanasin-hotel', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-rattanasin-hotel-wash-6', 'cust-rattanasin-hotel', '6', '6', '', '', 'wash'::price_service_type, 28),
  ('cpl-rattanasin-hotel-wash-7', 'cust-rattanasin-hotel', '7', '7', '', '', 'wash'::price_service_type, 23),
  ('cpl-rattanasin-hotel-wash-8', 'cust-rattanasin-hotel', '8', '8', '', '', 'wash'::price_service_type, 33),
  ('cpl-rattanasin-hotel-wash-9', 'cust-rattanasin-hotel', '9', '9', '', '', 'wash'::price_service_type, 28),
  ('cpl-rattanasin-hotel-wash-a02', 'cust-rattanasin-hotel', 'A02', 'A02', '', '', 'wash'::price_service_type, 30),
  ('cpl-rph-ranong-mri-wash-5', 'cust-rph-ranong-mri', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-rph-ranong-mri-wash-a02', 'cust-rph-ranong-mri', 'A02', 'A02', '', '', 'wash'::price_service_type, 20),
  ('cpl-rph-ranong-mri-wash-a06', 'cust-rph-ranong-mri', 'A06', 'A06', '', '', 'wash'::price_service_type, 20),
  ('cpl-rph-ranong-mri-wash-a27', 'cust-rph-ranong-mri', 'A27', 'A27', '', '', 'wash'::price_service_type, 8),
  ('cpl-rph-ranong-mri-wash-a28', 'cust-rph-ranong-mri', 'A28', 'A28', '', '', 'wash'::price_service_type, 8),
  ('cpl-ruangrat-hotel-wash-1', 'cust-ruangrat-hotel', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-ruangrat-hotel-wash-10', 'cust-ruangrat-hotel', '10', '10', '', '', 'wash'::price_service_type, 65),
  ('cpl-ruangrat-hotel-wash-11', 'cust-ruangrat-hotel', '11', '11', '', '', 'wash'::price_service_type, 60),
  ('cpl-ruangrat-hotel-wash-18', 'cust-ruangrat-hotel', '18', '18', '', '', 'wash'::price_service_type, 40),
  ('cpl-ruangrat-hotel-wash-3', 'cust-ruangrat-hotel', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-ruangrat-hotel-wash-4', 'cust-ruangrat-hotel', '4', '4', '', '', 'wash'::price_service_type, 6),
  ('cpl-ruangrat-hotel-wash-5', 'cust-ruangrat-hotel', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-ruangrat-hotel-wash-6', 'cust-ruangrat-hotel', '6', '6', '', '', 'wash'::price_service_type, 25),
  ('cpl-ruangrat-hotel-wash-7', 'cust-ruangrat-hotel', '7', '7', '', '', 'wash'::price_service_type, 20),
  ('cpl-ssru-wash-1', 'cust-ssru', '1', '1', '', '', 'wash'::price_service_type, 12),
  ('cpl-ssru-wash-10', 'cust-ssru', '10', '10', '', '', 'wash'::price_service_type, 70),
  ('cpl-ssru-wash-11', 'cust-ssru', '11', '11', '', '', 'wash'::price_service_type, 70),
  ('cpl-ssru-wash-1sp', 'cust-ssru', '1sp', '1', '', 'sp', 'wash'::price_service_type, 20),
  ('cpl-ssru-wash-21', 'cust-ssru', '21', '21', '', '', 'wash'::price_service_type, 10),
  ('cpl-ssru-wash-22', 'cust-ssru', '22', '22', '', '', 'wash'::price_service_type, 3),
  ('cpl-ssru-wash-23', 'cust-ssru', '23', '23', '', '', 'wash'::price_service_type, 30),
  ('cpl-ssru-wash-3', 'cust-ssru', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-ssru-wash-3sp', 'cust-ssru', '3sp', '3', '', 'sp', 'wash'::price_service_type, 10),
  ('cpl-ssru-wash-4', 'cust-ssru', '4', '4', '', '', 'wash'::price_service_type, 8),
  ('cpl-ssru-wash-4sp', 'cust-ssru', '4sp', '4', '', 'sp', 'wash'::price_service_type, 12),
  ('cpl-ssru-wash-5', 'cust-ssru', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-ssru-wash-5sp', 'cust-ssru', '5sp', '5', '', 'sp', 'wash'::price_service_type, 8),
  ('cpl-ssru-wash-6', 'cust-ssru', '6', '6', '', '', 'wash'::price_service_type, 28),
  ('cpl-ssru-wash-7', 'cust-ssru', '7', '7', '', '', 'wash'::price_service_type, 23),
  ('cpl-ssru-wash-7sp', 'cust-ssru', '7sp', '7', '', 'sp', 'wash'::price_service_type, 50),
  ('cpl-ssru-wash-8', 'cust-ssru', '8', '8', '', '', 'wash'::price_service_type, 33),
  ('cpl-ssru-wash-9', 'cust-ssru', '9', '9', '', '', 'wash'::price_service_type, 28),
  ('cpl-st-park-wash-1', 'cust-st-park', '1', '1', '', '', 'wash'::price_service_type, 12),
  ('cpl-st-park-wash-1sp', 'cust-st-park', '1sp', '1', '', 'sp', 'wash'::price_service_type, 18),
  ('cpl-st-park-wash-3', 'cust-st-park', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-st-park-wash-3sp', 'cust-st-park', '3sp', '3', '', 'sp', 'wash'::price_service_type, 8),
  ('cpl-st-park-wash-4', 'cust-st-park', '4', '4', '', '', 'wash'::price_service_type, 8),
  ('cpl-st-park-wash-5', 'cust-st-park', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-st-park-wash-6', 'cust-st-park', '6', '6', '', '', 'wash'::price_service_type, 28),
  ('cpl-st-park-wash-7', 'cust-st-park', '7', '7', '', '', 'wash'::price_service_type, 23),
  ('cpl-st-park-wash-8', 'cust-st-park', '8', '8', '', '', 'wash'::price_service_type, 33),
  ('cpl-st-park-wash-9', 'cust-st-park', '9', '9', '', '', 'wash'::price_service_type, 28),
  ('cpl-st-park-wash-a01ssp', 'cust-st-park', 'A01Ssp', 'A01', 'S', 'sp', 'wash'::price_service_type, 90),
  ('cpl-st-park-wash-a02', 'cust-st-park', 'A02', 'A02', '', '', 'wash'::price_service_type, 30),
  ('cpl-suk-hotel-wash-1', 'cust-suk-hotel', '1', '1', '', '', 'wash'::price_service_type, 8),
  ('cpl-suk-hotel-wash-12', 'cust-suk-hotel', '12', '12', '', '', 'wash'::price_service_type, 45),
  ('cpl-suk-hotel-wash-13', 'cust-suk-hotel', '13', '13', '', '', 'wash'::price_service_type, 40),
  ('cpl-suk-hotel-wash-14', 'cust-suk-hotel', '14', '14', '', '', 'wash'::price_service_type, 9),
  ('cpl-suk-hotel-wash-16', 'cust-suk-hotel', '16', '16', '', '', 'wash'::price_service_type, 8),
  ('cpl-suk-hotel-wash-17', 'cust-suk-hotel', '17', '17', '', '', 'wash'::price_service_type, 2),
  ('cpl-suk-hotel-wash-18', 'cust-suk-hotel', '18', '18', '', '', 'wash'::price_service_type, 40),
  ('cpl-suk-hotel-wash-1sp', 'cust-suk-hotel', '1sp', '1', '', 'sp', 'wash'::price_service_type, 12),
  ('cpl-suk-hotel-wash-3', 'cust-suk-hotel', '3', '3', '', '', 'wash'::price_service_type, 3),
  ('cpl-suk-hotel-wash-3sp', 'cust-suk-hotel', '3sp', '3', '', 'sp', 'wash'::price_service_type, 5),
  ('cpl-suk-hotel-wash-4', 'cust-suk-hotel', '4', '4', '', '', 'wash'::price_service_type, 7),
  ('cpl-suk-hotel-wash-4sp', 'cust-suk-hotel', '4sp', '4', '', 'sp', 'wash'::price_service_type, 11),
  ('cpl-suk-hotel-wash-5', 'cust-suk-hotel', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-suk-hotel-wash-5b', 'cust-suk-hotel', '5B', '5', 'B', '', 'wash'::price_service_type, 2),
  ('cpl-suk-hotel-wash-5sp', 'cust-suk-hotel', '5sp', '5', '', 'sp', 'wash'::price_service_type, 8),
  ('cpl-suk-hotel-wash-6', 'cust-suk-hotel', '6', '6', '', '', 'wash'::price_service_type, 25),
  ('cpl-suk-hotel-wash-6sp', 'cust-suk-hotel', '6sp', '6', '', 'sp', 'wash'::price_service_type, 38),
  ('cpl-suk-hotel-wash-7', 'cust-suk-hotel', '7', '7', '', '', 'wash'::price_service_type, 20),
  ('cpl-suk-hotel-wash-8', 'cust-suk-hotel', '8', '8', '', '', 'wash'::price_service_type, 30),
  ('cpl-suk-hotel-wash-8sp', 'cust-suk-hotel', '8sp', '8', '', 'sp', 'wash'::price_service_type, 45),
  ('cpl-suk-hotel-wash-9', 'cust-suk-hotel', '9', '9', '', '', 'wash'::price_service_type, 25),
  ('cpl-suk-hotel-wash-a01lsp', 'cust-suk-hotel', 'A01Lsp', 'A01', 'L', 'sp', 'wash'::price_service_type, 90),
  ('cpl-suk-hotel-wash-a01s', 'cust-suk-hotel', 'A01S', 'A01', 'S', '', 'wash'::price_service_type, 60),
  ('cpl-suk-hotel-wash-a01ssp', 'cust-suk-hotel', 'A01Ssp', 'A01', 'S', 'sp', 'wash'::price_service_type, 90),
  ('cpl-suk-hotel-wash-a02b', 'cust-suk-hotel', 'A02B', 'A02', 'B', '', 'wash'::price_service_type, 10),
  ('cpl-suk-hotel-wash-a06b', 'cust-suk-hotel', 'A06B', 'A06', 'B', '', 'wash'::price_service_type, 10),
  ('cpl-suk-hotel-wash-a18', 'cust-suk-hotel', 'A18', 'A18', '', '', 'wash'::price_service_type, 35),
  ('cpl-suk-hotel-wash-a19', 'cust-suk-hotel', 'A19', 'A19', '', '', 'wash'::price_service_type, 40),
  ('cpl-suk-hotel-wash-a23', 'cust-suk-hotel', 'A23', 'A23', '', '', 'wash'::price_service_type, 5),
  ('cpl-sunnyvale-wash-1', 'cust-sunnyvale', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-sunnyvale-wash-12', 'cust-sunnyvale', '12', '12', '', '', 'wash'::price_service_type, 45),
  ('cpl-sunnyvale-wash-13', 'cust-sunnyvale', '13', '13', '', '', 'wash'::price_service_type, 45),
  ('cpl-sunnyvale-wash-1sp', 'cust-sunnyvale', '1sp', '1', '', 'sp', 'wash'::price_service_type, 15),
  ('cpl-sunnyvale-wash-20', 'cust-sunnyvale', '20', '20', '', '', 'wash'::price_service_type, 100),
  ('cpl-sunnyvale-wash-3', 'cust-sunnyvale', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-sunnyvale-wash-3sp', 'cust-sunnyvale', '3sp', '3', '', 'sp', 'wash'::price_service_type, 10),
  ('cpl-sunnyvale-wash-4', 'cust-sunnyvale', '4', '4', '', '', 'wash'::price_service_type, 8),
  ('cpl-sunnyvale-wash-4sp', 'cust-sunnyvale', '4sp', '4', '', 'sp', 'wash'::price_service_type, 12),
  ('cpl-sunnyvale-wash-5lsp', 'cust-sunnyvale', '5Lsp', '5', 'L', 'sp', 'wash'::price_service_type, 10),
  ('cpl-sunnyvale-wash-5ssp', 'cust-sunnyvale', '5Ssp', '5', 'S', 'sp', 'wash'::price_service_type, 10),
  ('cpl-sunnyvale-wash-6', 'cust-sunnyvale', '6', '6', '', '', 'wash'::price_service_type, 28),
  ('cpl-sunnyvale-wash-6sp', 'cust-sunnyvale', '6sp', '6', '', 'sp', 'wash'::price_service_type, 38),
  ('cpl-sunnyvale-wash-7', 'cust-sunnyvale', '7', '7', '', '', 'wash'::price_service_type, 23),
  ('cpl-sunnyvale-wash-8', 'cust-sunnyvale', '8', '8', '', '', 'wash'::price_service_type, 35),
  ('cpl-sunnyvale-wash-8sp', 'cust-sunnyvale', '8sp', '8', '', 'sp', 'wash'::price_service_type, 45),
  ('cpl-sunnyvale-wash-9', 'cust-sunnyvale', '9', '9', '', '', 'wash'::price_service_type, 30),
  ('cpl-than-sila-wash-1', 'cust-than-sila', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-than-sila-wash-13', 'cust-than-sila', '13', '13', '', '', 'wash'::price_service_type, 45),
  ('cpl-than-sila-wash-17', 'cust-than-sila', '17', '17', '', '', 'wash'::price_service_type, 5),
  ('cpl-than-sila-wash-19', 'cust-than-sila', '19', '19', '', '', 'wash'::price_service_type, 70),
  ('cpl-than-sila-wash-4', 'cust-than-sila', '4', '4', '', '', 'wash'::price_service_type, 8),
  ('cpl-than-sila-wash-5', 'cust-than-sila', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-than-sila-wash-5sp', 'cust-than-sila', '5sp', '5', '', 'sp', 'wash'::price_service_type, 8),
  ('cpl-than-sila-wash-6', 'cust-than-sila', '6', '6', '', '', 'wash'::price_service_type, 28),
  ('cpl-than-sila-wash-6sp', 'cust-than-sila', '6sp', '6', '', 'sp', 'wash'::price_service_type, 42),
  ('cpl-than-sila-wash-7', 'cust-than-sila', '7', '7', '', '', 'wash'::price_service_type, 23),
  ('cpl-than-sila-wash-8', 'cust-than-sila', '8', '8', '', '', 'wash'::price_service_type, 33),
  ('cpl-than-sila-wash-9', 'cust-than-sila', '9', '9', '', '', 'wash'::price_service_type, 28),
  ('cpl-than-sila-wash-a01l', 'cust-than-sila', 'A01L', 'A01', 'L', '', 'wash'::price_service_type, 70),
  ('cpl-than-sila-wash-a16', 'cust-than-sila', 'A16', 'A16', '', '', 'wash'::price_service_type, 5),
  ('cpl-the-crest-wash-1', 'cust-the-crest', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-the-crest-wash-12', 'cust-the-crest', '12', '12', '', '', 'wash'::price_service_type, 45),
  ('cpl-the-crest-wash-16', 'cust-the-crest', '16', '16', '', '', 'wash'::price_service_type, 12),
  ('cpl-the-crest-wash-2', 'cust-the-crest', '2', '2', '', '', 'wash'::price_service_type, 4),
  ('cpl-the-crest-wash-21', 'cust-the-crest', '21', '21', '', '', 'wash'::price_service_type, 20),
  ('cpl-the-crest-wash-3', 'cust-the-crest', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-the-crest-wash-4', 'cust-the-crest', '4', '4', '', '', 'wash'::price_service_type, 8),
  ('cpl-the-crest-wash-5', 'cust-the-crest', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-the-crest-wash-6', 'cust-the-crest', '6', '6', '', '', 'wash'::price_service_type, 30),
  ('cpl-the-crest-wash-7', 'cust-the-crest', '7', '7', '', '', 'wash'::price_service_type, 25),
  ('cpl-the-crest-wash-8', 'cust-the-crest', '8', '8', '', '', 'wash'::price_service_type, 35),
  ('cpl-the-crest-wash-a04', 'cust-the-crest', 'A04', 'A04', '', '', 'wash'::price_service_type, 15),
  ('cpl-the-crest-wash-a07', 'cust-the-crest', 'A07', 'A07', '', '', 'wash'::price_service_type, 7),
  ('cpl-the-ele-wash-1', 'cust-the-ele', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-the-ele-wash-12', 'cust-the-ele', '12', '12', '', '', 'wash'::price_service_type, 45),
  ('cpl-the-ele-wash-13', 'cust-the-ele', '13', '13', '', '', 'wash'::price_service_type, 45),
  ('cpl-the-ele-wash-13sp', 'cust-the-ele', '13sp', '13', '', 'sp', 'wash'::price_service_type, 68),
  ('cpl-the-ele-wash-1c', 'cust-the-ele', '1C', '1', 'C', '', 'wash'::price_service_type, 10),
  ('cpl-the-ele-wash-1csp', 'cust-the-ele', '1Csp', '1', 'C', 'sp', 'wash'::price_service_type, 15),
  ('cpl-the-ele-wash-1sp', 'cust-the-ele', '1sp', '1', '', 'sp', 'wash'::price_service_type, 15),
  ('cpl-the-ele-wash-2', 'cust-the-ele', '2', '2', '', '', 'wash'::price_service_type, 3),
  ('cpl-the-ele-wash-3', 'cust-the-ele', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-the-ele-wash-3c', 'cust-the-ele', '3C', '3', 'C', '', 'wash'::price_service_type, 5),
  ('cpl-the-ele-wash-3csp', 'cust-the-ele', '3Csp', '3', 'C', 'sp', 'wash'::price_service_type, 8),
  ('cpl-the-ele-wash-3sp', 'cust-the-ele', '3sp', '3', '', 'sp', 'wash'::price_service_type, 8),
  ('cpl-the-ele-wash-4', 'cust-the-ele', '4', '4', '', '', 'wash'::price_service_type, 8),
  ('cpl-the-ele-wash-5', 'cust-the-ele', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-the-ele-wash-5c', 'cust-the-ele', '5C', '5', 'C', '', 'wash'::price_service_type, 5),
  ('cpl-the-ele-wash-5csp', 'cust-the-ele', '5Csp', '5', 'C', 'sp', 'wash'::price_service_type, 8),
  ('cpl-the-ele-wash-5sp', 'cust-the-ele', '5sp', '5', '', 'sp', 'wash'::price_service_type, 8),
  ('cpl-the-ele-wash-6', 'cust-the-ele', '6', '6', '', '', 'wash'::price_service_type, 28),
  ('cpl-the-ele-wash-6c', 'cust-the-ele', '6C', '6', 'C', '', 'wash'::price_service_type, 28),
  ('cpl-the-ele-wash-6csp', 'cust-the-ele', '6Csp', '6', 'C', 'sp', 'wash'::price_service_type, 42),
  ('cpl-the-ele-wash-7', 'cust-the-ele', '7', '7', '', '', 'wash'::price_service_type, 23),
  ('cpl-the-ele-wash-7c', 'cust-the-ele', '7C', '7', 'C', '', 'wash'::price_service_type, 23),
  ('cpl-the-ele-wash-7csp', 'cust-the-ele', '7Csp', '7', 'C', 'sp', 'wash'::price_service_type, 35),
  ('cpl-the-ele-wash-7sp', 'cust-the-ele', '7sp', '7', '', 'sp', 'wash'::price_service_type, 35),
  ('cpl-the-ele-wash-8', 'cust-the-ele', '8', '8', '', '', 'wash'::price_service_type, 33),
  ('cpl-the-ele-wash-8c', 'cust-the-ele', '8C', '8', 'C', '', 'wash'::price_service_type, 33),
  ('cpl-the-ele-wash-8csp', 'cust-the-ele', '8Csp', '8', 'C', 'sp', 'wash'::price_service_type, 50),
  ('cpl-the-ele-wash-9', 'cust-the-ele', '9', '9', '', '', 'wash'::price_service_type, 28),
  ('cpl-the-ele-wash-9c', 'cust-the-ele', '9C', '9', 'C', '', 'wash'::price_service_type, 28),
  ('cpl-the-ele-wash-9csp', 'cust-the-ele', '9Csp', '9', 'C', 'sp', 'wash'::price_service_type, 42),
  ('cpl-the-ele-wash-9sp', 'cust-the-ele', '9sp', '9', '', 'sp', 'wash'::price_service_type, 42),
  ('cpl-the-ele-wash-a01l', 'cust-the-ele', 'A01L', 'A01', 'L', '', 'wash'::price_service_type, 70),
  ('cpl-the-ele-wash-a01lsp', 'cust-the-ele', 'A01Lsp', 'A01', 'L', 'sp', 'wash'::price_service_type, 100),
  ('cpl-the-ele-wash-a01s', 'cust-the-ele', 'A01S', 'A01', 'S', '', 'wash'::price_service_type, 70),
  ('cpl-the-galla-wash-1', 'cust-the-galla', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-the-galla-wash-12', 'cust-the-galla', '12', '12', '', '', 'wash'::price_service_type, 45),
  ('cpl-the-galla-wash-13', 'cust-the-galla', '13', '13', '', '', 'wash'::price_service_type, 45),
  ('cpl-the-galla-wash-14', 'cust-the-galla', '14', '14', '', '', 'wash'::price_service_type, 10),
  ('cpl-the-galla-wash-15', 'cust-the-galla', '15', '15', '', '', 'wash'::price_service_type, 5),
  ('cpl-the-galla-wash-16', 'cust-the-galla', '16', '16', '', '', 'wash'::price_service_type, 12),
  ('cpl-the-galla-wash-17', 'cust-the-galla', '17', '17', '', '', 'wash'::price_service_type, 5),
  ('cpl-the-galla-wash-1sp', 'cust-the-galla', '1sp', '1', '', 'sp', 'wash'::price_service_type, 15),
  ('cpl-the-galla-wash-3', 'cust-the-galla', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-the-galla-wash-3sp', 'cust-the-galla', '3sp', '3', '', 'sp', 'wash'::price_service_type, 8),
  ('cpl-the-galla-wash-4', 'cust-the-galla', '4', '4', '', '', 'wash'::price_service_type, 8),
  ('cpl-the-galla-wash-5l', 'cust-the-galla', '5L', '5', 'L', '', 'wash'::price_service_type, 6),
  ('cpl-the-galla-wash-5s', 'cust-the-galla', '5S', '5', 'S', '', 'wash'::price_service_type, 5),
  ('cpl-the-galla-wash-6', 'cust-the-galla', '6', '6', '', '', 'wash'::price_service_type, 28),
  ('cpl-the-galla-wash-7', 'cust-the-galla', '7', '7', '', '', 'wash'::price_service_type, 23),
  ('cpl-the-galla-wash-8', 'cust-the-galla', '8', '8', '', '', 'wash'::price_service_type, 33),
  ('cpl-the-galla-wash-9', 'cust-the-galla', '9', '9', '', '', 'wash'::price_service_type, 28),
  ('cpl-the-galla-wash-a01s', 'cust-the-galla', 'A01S', 'A01', 'S', '', 'wash'::price_service_type, 70),
  ('cpl-the-galla-wash-a18', 'cust-the-galla', 'A18', 'A18', '', '', 'wash'::price_service_type, 35),
  ('cpl-the-iconic-hotel-wash-1', 'cust-the-iconic-hotel', '1', '1', '', '', 'wash'::price_service_type, 12),
  ('cpl-the-iconic-hotel-wash-3', 'cust-the-iconic-hotel', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-the-iconic-hotel-wash-4', 'cust-the-iconic-hotel', '4', '4', '', '', 'wash'::price_service_type, 8),
  ('cpl-the-iconic-hotel-wash-5', 'cust-the-iconic-hotel', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-the-iconic-hotel-wash-5c', 'cust-the-iconic-hotel', '5C', '5', 'C', '', 'wash'::price_service_type, 5),
  ('cpl-the-iconic-hotel-wash-5sp', 'cust-the-iconic-hotel', '5sp', '5', '', 'sp', 'wash'::price_service_type, 8),
  ('cpl-the-iconic-hotel-wash-6', 'cust-the-iconic-hotel', '6', '6', '', '', 'wash'::price_service_type, 28),
  ('cpl-the-iconic-hotel-wash-6c', 'cust-the-iconic-hotel', '6C', '6', 'C', '', 'wash'::price_service_type, 28),
  ('cpl-the-iconic-hotel-wash-6sp', 'cust-the-iconic-hotel', '6sp', '6', '', 'sp', 'wash'::price_service_type, 42),
  ('cpl-the-iconic-hotel-wash-7', 'cust-the-iconic-hotel', '7', '7', '', '', 'wash'::price_service_type, 23),
  ('cpl-the-iconic-hotel-wash-8', 'cust-the-iconic-hotel', '8', '8', '', '', 'wash'::price_service_type, 33),
  ('cpl-the-iconic-hotel-wash-8c', 'cust-the-iconic-hotel', '8C', '8', 'C', '', 'wash'::price_service_type, 33),
  ('cpl-the-iconic-hotel-wash-9', 'cust-the-iconic-hotel', '9', '9', '', '', 'wash'::price_service_type, 28),
  ('cpl-the-iconic-hotel-wash-a02', 'cust-the-iconic-hotel', 'A02', 'A02', '', '', 'wash'::price_service_type, 30),
  ('cpl-the-iconic-hotel-wash-a17', 'cust-the-iconic-hotel', 'A17', 'A17', '', '', 'wash'::price_service_type, 12),
  ('cpl-the-white-village-wash-1', 'cust-the-white-village', '1', '1', '', '', 'wash'::price_service_type, 12),
  ('cpl-the-white-village-wash-1l', 'cust-the-white-village', '1L', '1', 'L', '', 'wash'::price_service_type, 12),
  ('cpl-the-white-village-wash-1s', 'cust-the-white-village', '1S', '1', 'S', '', 'wash'::price_service_type, 12),
  ('cpl-the-white-village-wash-6', 'cust-the-white-village', '6', '6', '', '', 'wash'::price_service_type, 33),
  ('cpl-the-white-village-wash-7', 'cust-the-white-village', '7', '7', '', '', 'wash'::price_service_type, 28),
  ('cpl-the-white-village-wash-8', 'cust-the-white-village', '8', '8', '', '', 'wash'::price_service_type, 38),
  ('cpl-the-white-village-wash-9', 'cust-the-white-village', '9', '9', '', '', 'wash'::price_service_type, 32),
  ('cpl-tobedzz-wash-1', 'cust-tobedzz', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-tobedzz-wash-11c', 'cust-tobedzz', '11C', '11', 'C', '', 'wash'::price_service_type, 70),
  ('cpl-tobedzz-wash-12', 'cust-tobedzz', '12', '12', '', '', 'wash'::price_service_type, 45),
  ('cpl-tobedzz-wash-12sp', 'cust-tobedzz', '12sp', '12', '', 'sp', 'wash'::price_service_type, 68),
  ('cpl-tobedzz-wash-13', 'cust-tobedzz', '13', '13', '', '', 'wash'::price_service_type, 45),
  ('cpl-tobedzz-wash-16', 'cust-tobedzz', '16', '16', '', '', 'wash'::price_service_type, 12),
  ('cpl-tobedzz-wash-3', 'cust-tobedzz', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-tobedzz-wash-4', 'cust-tobedzz', '4', '4', '', '', 'wash'::price_service_type, 8),
  ('cpl-tobedzz-wash-5', 'cust-tobedzz', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-tobedzz-wash-6', 'cust-tobedzz', '6', '6', '', '', 'wash'::price_service_type, 28),
  ('cpl-tobedzz-wash-6sp', 'cust-tobedzz', '6sp', '6', '', 'sp', 'wash'::price_service_type, 42),
  ('cpl-tobedzz-wash-7', 'cust-tobedzz', '7', '7', '', '', 'wash'::price_service_type, 23),
  ('cpl-tobedzz-wash-8', 'cust-tobedzz', '8', '8', '', '', 'wash'::price_service_type, 33),
  ('cpl-tobedzz-wash-9', 'cust-tobedzz', '9', '9', '', '', 'wash'::price_service_type, 28),
  ('cpl-tobedzz-wash-a01l', 'cust-tobedzz', 'A01L', 'A01', 'L', '', 'wash'::price_service_type, 70),
  ('cpl-tobedzz-wash-a01s', 'cust-tobedzz', 'A01S', 'A01', 'S', '', 'wash'::price_service_type, 70),
  ('cpl-tobedzz-wash-a02', 'cust-tobedzz', 'A02', 'A02', '', '', 'wash'::price_service_type, 35),
  ('cpl-u-sabai-wash-1', 'cust-u-sabai', '1', '1', '', '', 'wash'::price_service_type, 10),
  ('cpl-u-sabai-wash-1sp', 'cust-u-sabai', '1sp', '1', '', 'sp', 'wash'::price_service_type, 15),
  ('cpl-u-sabai-wash-3', 'cust-u-sabai', '3', '3', '', '', 'wash'::price_service_type, 5),
  ('cpl-u-sabai-wash-3sp', 'cust-u-sabai', '3sp', '3', '', 'sp', 'wash'::price_service_type, 8),
  ('cpl-u-sabai-wash-5', 'cust-u-sabai', '5', '5', '', '', 'wash'::price_service_type, 5),
  ('cpl-u-sabai-wash-6', 'cust-u-sabai', '6', '6', '', '', 'wash'::price_service_type, 30),
  ('cpl-u-sabai-wash-6sp', 'cust-u-sabai', '6sp', '6', '', 'sp', 'wash'::price_service_type, 45),
  ('cpl-u-sabai-wash-7', 'cust-u-sabai', '7', '7', '', '', 'wash'::price_service_type, 25),
  ('cpl-u-sabai-wash-8', 'cust-u-sabai', '8', '8', '', '', 'wash'::price_service_type, 35),
  ('cpl-u-sabai-wash-9', 'cust-u-sabai', '9', '9', '', '', 'wash'::price_service_type, 30),
  ('cpl-u-sabai-wash-a27', 'cust-u-sabai', 'A27', 'A27', '', '', 'wash'::price_service_type, 10)
ON CONFLICT (customer_id, sku, service_type) DO UPDATE SET
  product_code  = EXCLUDED.product_code,
  size_code     = EXCLUDED.size_code,
  activity_code = EXCLUDED.activity_code,
  unit_price    = EXCLUDED.unit_price,
  is_active     = true,
  updated_at    = now();
